#ifndef MAZECAVEGENERATOR_MCG_VIEW_MANAGER_VIEW_H_
#define MAZECAVEGENERATOR_MCG_VIEW_MANAGER_VIEW_H_

#include "cave_manager.h"
#include "maze_manager.h"

#endif  // MAZECAVEGENERATOR_MCG_VIEW_MANAGER_VIEW_H_